# Override values for sharry.

image:
  tag: 1.8.0
  pullPolicy: IfNotPresent

ingress:
  main:
    enabled: true
    # -- Enable large file support with those annotations for nginx
    annotations:
      nginx.ingress.kubernetes.io/client-body-buffer-size: "2048m"
      nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
    hosts:
      - host: sharry.pleasenoddos.com
        paths:
          - path: /

resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 250Mi

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

persistence:
  data:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /tmp
    storageClass: sharry
    accessMode: ReadWriteOnce
    size: 30Gi

nodeSelector: {}
