# Default values for wiki.

image:
  # Override image
  repository: requarks/wiki
  pullPolicy: IfNotPresent
  tag: 2.5.201

controller:
  strategy:
    type: RollingUpdate

env:
  # -- mysql, postgres, mariadb, mssql or sqlite
  DB_TYPE: postgres
  # -- Host of the database
  DB_HOST: postgresql.postgresql
  # -- Port of the database
  DB_PORT: 5432

serviceAccount:
  # Specifies whether a service account should be created
  create: false

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  hosts:
    - host: wiki.pleasenoddos.com
      paths:
        - path: /

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: '1'
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 125Mi

nodeSelector:
  kubernetes.io/arch: amd64
